version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST_IP=${HOST_IP}
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata:
